### PR TITLE
Propublica link

### PR DESCRIPTION
**Pull request by thoo**
Hi Zach,
I did an update propublica link in README.md. Thanks.

### CODE REVIEW

**Comment by ZachGlassman** [comment]
@thoo assign me as a reviewer and I'd be happy to take a look, but lets merge from branches in this repo, not from forked repos.

**Comment by thoo** [comment]
Thank Zach. I will resubmit the pull request from the branch. Is there any branch we should use??

**Comment by ZachGlassman** [comment]
One that is well named is usually good, but you can call it whatever you want.

**Comment by ZachGlassman** [comment]
I'm going to close this, but add me to review when you resubmit.

**Pull request closed without merging**
